version: '3.7'
services:
# docker run -d -p 3306:3306 --name mysql-container --network mynetwork -e MYSQL_ROOT_PASSWORD=fontaine2019+ -v mysql_data2:/var/lib/mysql mysql:latest
  mysql-service:
    container_name: mysql-container
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fontaine2019+
    networks:
      - mynetwork
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql 
    
# docker run --name flask-container --network mynetwork -p 5000:5000 flask-app-image:latest
  flask-service:
    container_name: flask-container
    image: flask-app-image:latest
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - mysql-service
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  mysql_data:
